"""Render a key player's structured profile into a human-readable markdown document. PURE.

A RENDERER, not a decider — the exact contract of lib/notify.py. It takes an already-assembled
profile dict (from lib.intel.aggregate.build_profile) and returns ``{md, content_hash, bioguide}``.
It never reads config, the ledger, the network, or a trading limit; it never calls the clock.

THE INVARIANT: the ``.md`` is a rendered VIEW over intel.db, never the source of truth. Its content
is a render of what the member's SPONSORED SECTIONS mechanically do — not an LLM essay about the
person. Every claim traces to (doc_id, sec, verbatim span). Because bill text is attacker-influenced
public text, a profile must never be re-ingested as instructions; it is output only.

DIFF STABILITY: content_hash covers the semantic skeleton (roles + per-ticker posture + spans),
NOT any timestamp — so a weekly re-render with unchanged inputs produces a byte-identical body and a
stable diff. There is deliberately no ``generated_at`` field in the hashed body.
"""
from __future__ import annotations

import hashlib
import json

_GENERATED_HEADER = "<!-- Code generated by tick.py intel-profile — DO NOT EDIT. A VIEW over intel.db. -->"


def content_hash(profile: dict) -> str:
    """Hash the semantic skeleton only (bioguide + roles + per-ticker posture/score/spans),
    excluding any timestamp, so an unchanged profile re-renders identically."""
    skel = {
        "bioguide": profile.get("bioguide"),
        "roles": profile.get("roles"),
        "tickers": {t: {"posture": p.get("posture"), "score": p.get("score"),
                        "spans": [e.get("span") for e in p.get("evidence", [])]}
                    for t, p in profile.get("tickers", {}).items()},
    }
    return hashlib.sha256(json.dumps(skel, sort_keys=True, default=str).encode()).hexdigest()[:16]


def _posture_word(p: str) -> str:
    return {"helps": "TAILWIND", "hurts": "THREAT", "mixed": "MIXED", "neutral": "neutral"}.get(p, p)


def render(profile: dict, *, as_of: str = "") -> dict:
    """profile dict -> {md, content_hash, bioguide}. ``as_of`` is stamped in the frontmatter for
    the human but is NOT part of content_hash (diff stability)."""
    ch = content_hash(profile)
    name = profile.get("name") or profile.get("bioguide")
    roles = profile.get("roles") or []
    tickers = profile.get("tickers") or {}

    lines = [_GENERATED_HEADER, "---",
             "schema: 1",
             f"bioguide: {profile.get('bioguide')}",
             f"congress: {profile.get('congress')}",
             f"as_of: {as_of}",
             f"input_hash: {ch}",
             "source_of_truth: state/ledger.db#intel_section_impact",
             "---",
             f"# {name}",
             ""]

    # Power — WHY this person is a key player (the structural power to affect outcomes)
    lines.append("## Power (point-in-time)")
    if roles:
        for r in roles:
            bits = [b for b in (r.get("role"), r.get("committee"), r.get("chamber")) if b]
            lines.append(f"- {' · '.join(str(b) for b in bits)}")
    else:
        lines.append("- (no recorded gavel/leadership role this congress)")
    lines.append("")

    # Revealed industry posture — derived from what they SPONSORED, every claim traced
    lines.append("## Revealed posture (from sponsored sections)")
    if not tickers:
        lines.append("_No sponsored section reached the book's universe. Nothing to report — this "
                     "is the correct, common outcome._")
    for tk, p in tickers.items():
        lines.append(f"### {tk} — **{_posture_word(p['posture'])}**  "
                     f"(score {p['score']:+.2f}, {p['n_helps']} helps / {p['n_hurts']} hurts)")
        for e in p.get("evidence", []):
            loc = f"{e.get('doc_id')} §{e.get('sec')}"
            title = f" ({e.get('title')})" if e.get("title") else ""
            lines.append(f"- **{loc}**{title} — {e.get('direction')} "
                         f"[{e.get('confidence')}, verifier: {e.get('verdict') or 'none'}]")
            span = (e.get("span") or "").strip()
            if span:
                lines.append(f"  > \"{span[:240]}\"")
        lines.append("")

    lines.append("---")
    lines.append(f"_Derived from {profile.get('n_documents', 0)} sponsored document(s). "
                 "Every claim above traces to a bill section and a verbatim span; this file is a "
                 "view over the ledger, not a source of truth._")
    return {"md": "\n".join(lines) + "\n", "content_hash": ch, "bioguide": profile.get("bioguide")}
